### PR TITLE
Require bluesky-social/atproto for .github/workflows/build-and-push-*

### PR DESCRIPTION
**Pull request by jcsalterego**
The build and push images actions fail for forks which in turn create a lot of failure noise.

This PR runs the actions only for the original `bluesky-social/atproto` repository on the `main` branch.

Do not merge if you wish to build and push main branches from other repositories.

### CODE REVIEW

**Comment by jcsalterego** [comment]
Test failures appear to be unrelated.

**Review by bnewbold — APPROVED** [review]
This looks good to me, seems to be the idiomatic way to accomplish this, and should reduce friction/annoyance for third party devs.

:thinking: we should probably also do this for `social-app`, `indigo`, and `did-method-plc`

cc: @Jacob2161 for a second set of eyes in case there are unintended consequences on our build pipeline.

**Comment by jcsalterego** [comment]
One thought is it still might be useful to build the images (but not push) in all branches except main, so there aren't any surprises after PRs are merged. Those should probably exist as a separate set of workflows (possibly in a separate PR as well).

**Comment by Jacob2161** [comment]
Seems smart, thanks!

**Comment by dholms** [comment]
sweet thanks for this!

**Pull request merged**
