### PR TITLE
Add missing labels that are available on the moderation tool

### PR DESCRIPTION
**Pull request by foysalit**

### CODE REVIEW

**Comment by devinivy** [comment]
@pfrazee mind taking a quick peek at this when you find a moment?

**Review by pfrazee — COMMENTED** [review]
+1 to the change but you're modifying generated code. You need to place these definitions in the `.json` files under `./definitions` and then run `yarn codegen`

**Comment by foysalit** [comment]
> +1 to the change but you're modifying generated code. You need to place these definitions in the `.json` files under `./definitions` and then run `yarn codegen`

definition of 🤦🏽‍♂️

Moved everything over to the json definition now @pfrazee

**Review by pfrazee — APPROVED** [review]
All good! Looks good tme

**Pull request merged**
