### PR TITLE
Fix lexicon. "format" instead of "ref" in type "string"

### PR DESCRIPTION
**Pull request by MarshalX**
my Python codegen failed on it. let me know pls if the lexicon has been changed and it's not a typo

### CODE REVIEW

**Comment by MarshalX** [comment]
according to the lexicon package string type can't have "ref"
https://github.com/bluesky-social/atproto/blob/36d4e5bb003268a7871df27aec23b0e0ff8cc479/packages/lexicon/src/types.ts#L39-L52

but test has been failed

**Comment by myConsciousness** [comment]
I think it's a typo, `at-uri` is not a ref but format

**Comment by MarshalX** [comment]
> 

good to know. but why tests failed with  "Failed to parse schema definition app.bsky.graph.defs"

**Comment by MarshalX** [comment]
ah wait. the latest commit in main failed tests https://github.com/bluesky-social/atproto/commit/36d4e5bb003268a7871df27aec23b0e0ff8cc479

**Comment by MarshalX** [comment]
well, at least a tried to regen it

**Comment by devinivy** [comment]
Hey, sorry about that— the CI broke with a merge from last night that needed to be rebased.  I think if you rebase this on `main` or merge `main` into this branch then we should be good to go.  The change here looks good, thanks!

**Comment by MarshalX** [comment]
@devinivy " @atproto/bsky@0.0.0 codegen" with a lot of edits. Is it fine?

**Comment by devinivy** [comment]
@Matrix89 this looks good as-is, no need to worry about the bsky package at the moment.

Re: making the lex document validation strict, I support that.  @dholms sound reasonable to you?  I suppose there's some thorny compatibility/upgradeability questions there if were actually part of the lexicon spec, but for the purposes of our tooling I think it's a good call.

**Pull request merged**
