### PR TITLE
relax restriction on handle length in PDS

### LINKED ISSUE #2391: handle length restriction is too short.
**Describe the bug**

PDS restricts the length of the handle to 30 at below, which is too short for practical purposes.
below line (handle.length) means total length of user name part + FQDN part  is up to 30.

[RFC1035](https://datatracker.ietf.org/doc/html/rfc1035#section-2.3.4) defines maximum length of FQDN is 255. then, it needs relax restriction on handle length, up to 255.

https://github.com/bluesky-social/atproto/blob/f5c830a33b6774c4572973df103d4a861bbc5e7d/packages/pds/src/handle/index.ts#L89-L90

**To Reproduce**

```bash
# send request
curl -L -X POST 'https://pds-subdomain.mydomain.com/xrpc/com.atproto.server.createAccount' \
-H 'Content-Type: application/json'  -H 'Accept: application/json' \
-d '{ "email": "user567890@mydomain.com" ,"handle": "user567890.pds-subdomain.mydomain.com", "password": "shortpass" }' 

# result:
 {"error":"InvalidHandle","message":"Handle too long"}
```

1. starts PDS and sends above createAccount request.

NOTE: this restriction is not raised when testing with atproto/packages/dev-env.

**Expected behavior**

the above request should succeed since FQDN part meets RFC condition.

**Details**

use PDS docker image distributed at https://github.com/bluesky-social/pds or https://github.com/bluesky-social/atproto/tree/main/services/pds
- Operating system:
- Node version:

**Additional context**

### PR DESCRIPTION
**Pull request by itaru2622**
fix #2391

### CODE REVIEW

**Comment by itaru2622** [comment]
the code followed the discussion in the issue #2391.

**Comment by bnewbold** [comment]
@itaru2622 this is simple and resolves a long-standing issue for self-hosted PDS operators. thanks!

could you add a couple additional tests to `handle-validation.test.ts`, for this new logic?

for example, a longer base domain in the `domains` list, and an example of a less-than-18-char handle working with that (even if longer than 30 total chars), and a ~20 char handle on the `.test` domain (which would be less than 30 chars total, but still invalid). you'd have to add a helper for "expectNotThrow" or similar I think.

if you have trouble adding these LMK and I an take a pass at it.

**Comment by itaru2622** [comment]
@bnewbold  test case added in handle-validation.test.ts

I hope below tests meet your request. please refer the code for detail.

```nodejs
    expectThrow('usernamepartover18c.test',    'Handle too long')                                                                                                        
    expectNotThrow('u23456789012345678.test',  'safe up to 18 chars in first segment of the handle')                                                                     
    expectThrow('usernamepartover18c.loooooooooooooooooong-pds-over18chars.mybsky.mydomain.com',   'Handle too long')                                                    
    expectNotThrow('u23456789012345678.loooooooooooooooooong-pds-over18chars.mybsky.mydomain.com', 'safe long domain in the handle')
```

**Review by dholms — APPROVED** [review]
Sweet this looks good 👍 

Thanks for the tests as well

**Comment by bnewbold** [comment]
Two CI test issues:

- lint issues with the new test code
- many of the example handles in `pds/tests/seeds/users-bulk.ts` have become invalid and need to be updated; this impacts tests in other packages that use those accounts

I can try to resolve both of these from a new branch, and will update this PR when I get around to that.

**Comment by bnewbold** [comment]
I can't update this PR (the branch is in a different repo), but I created this new PR on top of it, which resolves the build issues: https://github.com/bluesky-social/atproto/pull/2392

**Comment by bnewbold** [comment]
@itaru2622 I merged the above-linked PR, which included your commits. I'm going to close this PR now.

It may take us a while to update the PDS "distribution".

**Comment by itaru2622** [comment]
@bnewbold thank you for your work on this PR and fixing.

I confirmed my codes were merged into latest main branch.
so, I will close this PR.

**Comment by itaru2622** [comment]
This PR has been taken over by #2410 and has been merged into main branch, so this PR is closed.

**Pull request closed without merging**
