### PR TITLE
packages/pg becomes packages/dev-infra with some cleanup

### PR DESCRIPTION
**Pull request by jcsalterego**
This is against @devinivy's feature branch in #1368 and builds on top of the packages/pg changes for adding redis.

* Renames `pg` to `dev-infra`, since it's no longer just postgres. `infra` and `docker` sounded too ambiguous/confusing. Maybe it could be `test-infra`?
* Extracted common logic and checks into `_common.sh` and all the `with-test-db.sh` and `with-test-redis-and-db.sh` scripts have to do is `source _common`, set `SERVICES="redis_test"` and call `main`

### CODE REVIEW

**Comment by jcsalterego** [comment]
Ignore the misleading branch name, lol.

**Comment by jcsalterego** [comment]
@devinivy TIL `source` requires bash at least. I've kept it at `sh` level in the spirit of the original script.

**Comment by dholms** [comment]
nice this looks really nifty 👍 

I'd been wanting to formalize this package a little bit more now that we're adding new functionality to it & I think this does so nicely

let me play around with it a bit locally & we can see about getting it merged

**Comment by jcsalterego** [comment]
@dholms woohoo! Thanks for trying it out.

**Comment by jcsalterego** [comment]
The latest test failures appear to be 500s returned by actor-search.ts but I don't believe they're related to changes in this PR:

```
2023-08-01T05:44:45.4122250Z @atproto/pds: FAIL PDS tests/views/actor-search.test.ts (34.428 s)
2023-08-01T05:44:45.4123262Z @atproto/pds:   pds user search views
2023-08-01T05:44:45.4124094Z @atproto/pds:     ✕ typeahead gives relevant results (1 ms)
2023-08-01T05:44:45.4124887Z @atproto/pds:     ✕ typeahead gives empty result set when provided empty term
2023-08-01T05:44:45.4125633Z @atproto/pds:     ✕ typeahead applies limit
2023-08-01T05:44:45.4126231Z @atproto/pds:     ✕ search gives relevant results
2023-08-01T05:44:45.4126955Z @atproto/pds:     ✕ search gives empty result set when provided empty term
2023-08-01T05:44:45.4127618Z @atproto/pds:     ✕ paginates
2023-08-01T05:44:45.4128932Z @atproto/pds:     ✕ search handles bad input
2023-08-01T05:44:45.4129549Z @atproto/pds:     ✕ search blocks by actor takedown
```

**Pull request merged**
