### PR TITLE
Attach record URI to listItemView

### PR DESCRIPTION
**Pull request by intrnl**
Fixes https://github.com/bluesky-social/atproto/issues/1622

### CODE REVIEW

**Comment by intrnl** [comment]
Not really sure how the tests are being done, it seems like running `pnpm test:withFlags --updateSnapshot` is resulting in a lot of diffs being generated, with the notable one being the invalid handles that all of the users now has

I don't think I've strayed from the instructions, even starting the dev environment leads to all the users having invalid handle.

**Comment by gildaswise** [comment]
Is there any issue with this one? It would really help managing actor removal on lists

**Review by dholms — APPROVED** [review]
This looks good to me & I agree the uri of the item should come down on the view

This is technically a breaking change in the lexicon, but it should be fine to roll out while we're not federated yet. I'll double check with @pfrazee on this to make sure it's good

**Comment by pfrazee** [comment]
Yeah this is safe for now

**Pull request merged**
