### PR TITLE
Follow-on cleanup after #2483

### PR DESCRIPTION
**Pull request by lindner**
- Change tests to use AtpClient instead of the deprecated BskyClient

### CODE REVIEW

**Comment by bnewbold** [comment]
docker/CI/github have been really struggling recently; I think the CI failures are due to infra issues for now. Will need to loop back after a few hours for the infra issues to settle and retry those runs.

**Comment by lindner** [comment]
Looks like all tests pass.  Looking forward to more PRs :-D

**Comment by bnewbold** [comment]
cc: @devinivy @matthieusieben

**Review by matthieusieben — APPROVED** [review]

**Comment by matthieusieben** [comment]
There is so much deprecated stuff that was introduced with that change.. thanks for helping us get rid of it 💙

**Pull request merged**
