### PR TITLE
Update atproto source license to MIT/Apache2

### PR DESCRIPTION
**Pull request by bnewbold**
Had consensus on this from discussion a week or two back. Copied the license files and general structure from did-method-plc (which we updated months ago), with very minor grammar updates and link fixes.

Notified external contributors and getting sign-offs in this issue thread: https://github.com/bluesky-social/atproto/issues/1786

Will give that a couple days before merging (unless 💯 reply sooner).

### CODE REVIEW

**Comment by bnewbold** [comment]
External contributors all signed-off on this, so ready for review and merge.

@pfrazee @dholms @devinivy @estrattonbailey

**Review by estrattonbailey — APPROVED** [review]
LGTM — we could add a changeset so this publishes to npm too!

CC @dholms just wanna confirm that we can publish all these and there's nothing in-flight that we don't want to release.

**Review by dholms — APPROVED** [review]
Looks good 👍 

I'm game to publish & I don't think anythign should be holding it up 👍

**Review by devinivy — APPROVED** [review]
💎

**Review by pfrazee — APPROVED** [review]
👍

**Pull request merged**
