### PR TITLE
Email templates at

### PR DESCRIPTION
**Pull request by estrattonbailey**

### CODE REVIEW

**Comment by estrattonbailey** [comment]
CI failure looks unrelated

**Review by dholms — APPROVED** [review]
sweet 👌 

re-running CI

**Comment by surfdude29** [comment]
Sorry for giving slightly unrelated feedback here, but I just got my first sign-in email in the new format and I was thinking maybe a background for the logo might be a good idea for users who are viewing it in dark mode?

It currently looks like this for me:
CF92B1C9-9684-4480-8ECC-C3A8042DEE49

Also, is it intentional that the code is shown in lowercase? It gets converted to uppercase when you paste it in, it seems.

**Comment by estrattonbailey** [comment]
@surfdude29 ah interesting. What email client are you using?

**Comment by surfdude29** [comment]
This was a screenshot from the Fastmail app on iOS. It shows up fine in light mode of course:

0300C135-043C-457C-ADBA-FE3BF6C321AE

**Comment by estrattonbailey** [comment]
My googling seems to tell me that I can't control this very well without lots of edge cases (email dev, ugh). I think if anything I'll just adjust that image so it looks decent in light or dark mode. Thanks for the shout!

**Comment by surfdude29** [comment]
No worries 👍

**Comment by estrattonbailey** [comment]
Ya know, actually I think this might not be so bad, did a little testing. Need to set up a dark mode but I'll give it a shot in a near term, def looks icky in dark mode. I use Fastmail too 😅

**Comment by surfdude29** [comment]
Nice, thanks 🙏

I've been with Fastmail since 2003, I'm very happy with them :)

**Pull request merged**
