### PR TITLE
Thread mutes

### PR DESCRIPTION
**Pull request by dholms**
⚠️ WIP ⚠️

### CODE REVIEW

**Comment by pfrazee** [comment]
Similar to other kinds of mutes, I need to have "thread muted" state attached to posts when they're served so that I can correctly display the mute/unmute toggle.

If we don't want to pay that overhead everywhere I can request that state when the dropdown opens but I dont love the latency that will introduce to the UI

**Comment by dholms** [comment]
ah right... yup forgot about that

how should thread mutes work with getTimeline feed? those posts will still show up right?

**Comment by pfrazee** [comment]
Yep correct. Also I'm applying this filter clientside right now -- not sure 100% what the plan is for server/client filtering of notifs but I have all the needed logic (for thread muting) in the client

**Comment by dholms** [comment]
closing for now - probably need a new pass on this

i'll keep the branch around in case we come back to it

**Pull request closed without merging**
