### PR TITLE
Include limited viewer info on blocked post

### PR DESCRIPTION
**Pull request by dholms**
includes limited viewer info (blocking & blockedBy) on blocked posts. This helps the UI display the correct prompt.

One little point of friction: the `viewer` here is different  from the `viewer` on post (post v actor). Do we want to adjust the property name at all? `viewerActor` feels kinda sloppy

### CODE REVIEW

**Comment by pfrazee** [comment]
🙏 muchos gracias this is perf

> One little point of friction: the viewer here is different from the viewer on post (post v actor). Do we want to adjust the property name at all? viewerActor feels kinda sloppy

I'm not overly bothered by this, but one thing we could consider doing is

```
uri: string
blocked: true
author: {
  did: string
  viewer: Viewer
}
```

We know the did already from the URL so it doesn't violate anything, and it resolves this awkwardness.

**Comment by dholms** [comment]
yeah I like that 👍

**Comment by pfrazee** [comment]
do you intend to make author optional? (we can get away with a breaking change here, I think). Otherwise +1

**Comment by dholms** [comment]
good call - I think we want author to be required but viewer to be optional

**Comment by pfrazee** [comment]
Thanks!

**Pull request merged**
