### PR TITLE
Finalize support for new moderation report reasons

### PR DESCRIPTION
**Pull request by devinivy**
Ideally in the future codegen will help us with these kinds of unions— this should conclude some of the "manual" work to support the new moderation report types.

### CODE REVIEW

**Comment by bnewbold** [comment]
@devinivy when I did a grep of the codebase for REASONSPAM, this database table line came up:
https://github.com/bluesky-social/atproto/blob/main/packages/pds/src/db/tables/moderation.ts#L46

I'm not sure if that comes through as an ENUM, or if that behavior is different in sqlite or postgresql (hopefully not an issue!)

there are also some existing tests the new values could slot in to fairly easily, though i'm not sure that is blocking

**Comment by bnewbold** [comment]
oh, I see, you do update that table def

**Comment by devinivy** [comment]
Yep yep!  It's just a typedef used at the app level— in the database these are varchars rather than postgres enums.  So I think we should be all good.

**Comment by bnewbold** [comment]
LGTM. added @dholms as a reviewer if a more formal lookover needed

**Review by dholms — APPROVED** [review]
LGTM 👍 just wondering if we want a "reason illegal" in here

**Pull request merged**
